# Generated by Django 4.2.11 on 2024-04-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('plt', 'Platinum365'), ('gld', 'Gold180'), ('slv', 'Silver90')], max_length=3)),
                ('cost', models.CharField(choices=[('365', '365'), ('180', '180'), ('90', '90')], max_length=3)),
                ('validity', models.CharField(choices=[('365', '365'), ('180', '180'), ('90', '90')], max_length=3)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_num', models.CharField(max_length=12)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('plan_renewal_date', models.DateField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.plan')),
            ],
        ),
    ]
